# Generated by Django 3.1.7 on 2021-03-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_post',
            new_name='blog_content',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_views',
            field=models.IntegerField(default=0),
        ),
    ]
